plugin:
    name: 'jointoit.getquote::lang.plugin.name'
    description: 'jointoit.getquote::lang.plugin.description'
    author: jointoit
    icon: oc-icon-bar-chart-o
    homepage: ''
navigation:
    Quotes:
        label: 'Website leads'
        url: jointoit/getquote/quotes
        icon: icon-bar-chart-o
