list: $/rewqp/getquote/models/quotes/columns.yaml
modelClass: Rewqp\GetQuote\Models\Quotes
title: Quotes
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'rewqp/getquote/quotes/update/:id'
